### PR TITLE
AutoStake (Formerly BlockNgine)

### PR DESCRIPTION
**Pull request by BlockNgine**

### CODE REVIEW

**Review by arnabghose997 — CHANGES_REQUESTED** [review]
@BlockNgine  The `minimum self delegation` should be `100000000000`, instead of `1`.

Instead of editing you current gentx, you have basically create a new gentx, with the above mentioned change and push it to this PR

**Comment by BlockNgine** [comment]
Changed, thanks

**Review by arnabghose997 — APPROVED** [review]
@BlockNgine 

Congratulations on being selected as a testnet validator! Keep an eye on this repo for `final_genesis.json` and `final_peers.json`.

We are expected to start our blockchain nodes on 28th September, 4:30 PM UTC

**Comment by BlockNgine** [comment]
Thanks,
Watch => All Activity done,
we are prepared and ready to go.

**Comment by arnabghose997** [comment]
@BlockNgine 

The `final_genesis.json` and `final_peers.txt` has been corrected and updated. Please make sure to incorporate it. Follow the below link for next steps:

https://github.com/hypersign-protocol/networks/tree/master/testnet/jagrat#after-final-genesis-release

**Pull request merged**
