### PR TITLE
landeros gentx+peer

### PR DESCRIPTION
**Pull request by landerosua**

### CODE REVIEW

**Comment by landerosua** [comment]
> @landerosua The `minimum self delegation` should be `100000000000`, instead of `1`. Please make the necessary change.

The genth file has been updated according to the required parameters.

**Review by arnabghose997 — CHANGES_REQUESTED** [review]
@landerosua 

It seems you have directly edited the gentx file. This would cause an error, since your earlier gentx has a signature.

So, basically you have to create a new gentx file (by following the pre genesis validator steps) and push it to this PR.

**Comment by landerosua** [comment]
> It seems you have directly edited the gentx file. This would cause an error, since your earlier gentx has a signature.
> 
> So, basically you have to create a new gentx file (by following the pre genesis validator steps) and push it to this PR.

@arnabghose997 No, the edit was done by regenerating new file. You may notice that the signature is different.

**Comment by arnabghose997** [comment]
@landerosua Oops my apologies! I didn't notice the signature change. Thanks for the update

**Review by arnabghose997 — COMMENTED** [review]
LGTM

**Review by arnabghose997 — APPROVED** [review]
@landerosua 

Congratulations on being selected as a testnet validator! Keep an eye on this repo for `final_genesis.json` and `final_peers.json`.

We are expected to start our blockchain nodes on 28th September, 4:30 PM UTC

**Comment by arnabghose997** [comment]
@landerosua 

The `final_genesis.json` and `final_peers.txt` has been corrected and updated. Please make sure to incorporate it. Follow the below link for next steps:

https://github.com/hypersign-protocol/networks/tree/master/testnet/jagrat#after-final-genesis-release

**Pull request merged**
