### PR TITLE
Perfect_Team gentx and peer

### PR DESCRIPTION
**Pull request by GolDSnakeR**

### CODE REVIEW

**Review by arnabghose997 — APPROVED** [review]
@GolDSnakeR 

Congratulations on being selected as a testnet validator! Keep an eye on this repo for `final_genesis.json` and `final_peers.json`.

We are expected to start our blockchain nodes on 28th September, 4:30 PM UTC

**Comment by GolDSnakeR** [comment]
Guys, thank you so much for choosing me as a validator. I am responsible in my work)

**Comment by GolDSnakeR** [comment]
Yes, thanks. I'm in the process of launching. Be so kind as to add a validator role to me in the discord. I joined a long time ago, but for some reason I didn't get the role. My username is in the discord - Aleksey#1658

**Comment by arnabghose997** [comment]
@GolDSnakeR I have assigned you the validator role in Discord. See you soon in our testnet :)

**Comment by GolDSnakeR** [comment]
Thank you very much! The role appeared. My discord didn't want to get attached for some reason. The node is configured, we are waiting for the network to start.

**Pull request merged**
