### PR TITLE
Create gentx-Enigma.json

### PR DESCRIPTION
**Pull request by Enigma-Validator**

### CODE REVIEW

**Review by arnabghose997 — CHANGES_REQUESTED** [review]
@Enigma-Validator Hi. Following fields in your gentx file needs to be changed:

1. Staking denom should be `uhid`, instead of `uqck`
2. Staking amount should be `100000000000` (This is expected from all validators)
3. Minimum self delegation should be `100000000000`

**Comment by Enigma-Validator** [comment]
Corrected !
Thanks for your review

**Comment by arnabghose997** [comment]
@Enigma-Validator In the latest gentx change, the `minimum self delegation` is still set to 1. It should be `100000000000`.

**Comment by Enigma-Validator** [comment]
@arnabghose997 done

**Review by arnabghose997 — APPROVED** [review]
@Enigma-Validator 

Congratulations on being selected as a testnet validator! Keep an eye on this repo for `final_genesis.json` and `final_peers.json`.

We are expected to start our blockchain nodes on 28th September, 4:30 PM UTC

**Comment by arnabghose997** [comment]
@Enigma-Validator 

The `final_genesis.json` and `final_peers.txt` has been corrected and updated. Please make sure to incorporate it. Follow the below link for next steps:

https://github.com/hypersign-protocol/networks/tree/master/testnet/jagrat#after-final-genesis-release

**Pull request merged**
