### PR TITLE
Create gentx-cryptech.json

### PR DESCRIPTION
**Pull request by dvjromashkin**
Gentx from Cryptech Team.

### CODE REVIEW

**Comment by arnabghose997** [comment]
@dvjromashkin 
It seems that you have raised two PRs (one for gentx, another for peer):

- https://github.com/hypersign-protocol/networks/pull/72
- https://github.com/hypersign-protocol/networks/pull/73

We will only consider the PR which you have provided in the KYC form. So, if you have provided this PR in the KYC form, please close the other PR, add the missing file in this PR.

**Comment by dvjromashkin** [comment]
done


>

**Review by arnabghose997 — APPROVED** [review]
@dvjromashkin 

Congratulations on being selected as a testnet validator! Keep an eye on this repo for `final_genesis.json` and `final_peers.json`.

We are expected to start our blockchain nodes on 28th September, 4:30 PM UTC

**Comment by arnabghose997** [comment]
@dvjromashkin 

The `final_genesis.json` and `final_peers.txt` has been corrected and updated. Please make sure to incorporate it. Follow the below link for next steps:

https://github.com/hypersign-protocol/networks/tree/master/testnet/jagrat#after-final-genesis-release

**Pull request merged**
