### PR TITLE
gentx-StakeBroker.json

### PR DESCRIPTION
**Pull request by Neschadin**

### CODE REVIEW

**Review by arnabghose997 — APPROVED** [review]
@Neschadin 

Congratulations on being selected as a testnet validator! Keep an eye on this repo for `final_genesis.json` and `final_peers.json`.

We are expected to start our blockchain nodes on 28th September, 4:30 PM UTC

**Comment by arnabghose997** [comment]
@Neschadin 

I just noticed your review comment now, where you are changing your gentx file. So, basically once a gentx file is generated, you are not supposed to make any manual changes to it as there's a signature associated with the gentx file.

Since, we are running short of time for the tesnet launch, I will basically revert the change on your behalf. You don't have to make any changes.

The updated `final_genesis.json` will be published soon. Will let you know in this PR and in the Discord Server.

**Comment by Neschadin** [comment]
> Since, we are running short of time for the tesnet launch, I will basically revert the change on your behalf. You don't have to make any changes.
> 
ok, no problem. I am staying with the original version.

**Comment by arnabghose997** [comment]
The `final_genesis.json` and `final_peers.txt` has been corrected and updated. Please make sure to incorporate it. Follow the below link for next steps:

https://github.com/hypersign-protocol/networks/tree/master/testnet/jagrat#after-final-genesis-release

**Pull request merged**
