### PR TITLE
add polkachu.com gentx

### PR DESCRIPTION
**Pull request by PolkachuIntern**

### CODE REVIEW

**Comment by arnabghose997** [comment]
@PolkachuIntern  The denom in your gentx file is `uhids`. Please make sure to change it to `uhid`

**Review by arnabghose997 — CHANGES_REQUESTED** [review]
@PolkachuIntern  The denom in your gentx file is `uhids`. You have to basically create a new gentx, which will have the correct denom (which is `uhid`) and commit that gentx in this PR. Also the minimum self delegation should be `100000000000` instead of `1`

**Comment by PolkachuIntern** [comment]
Fixed. Thanks for letting me know. I was careless in my initial submission.

**Review by arnabghose997 — APPROVED** [review]
@PolkachuIntern 

Congratulations on being selected as a testnet validator! Keep an eye on this repo for `final_genesis.json` and `final_peers.json`.

We are expected to start our blockchain nodes on 28th September, 4:30 PM UTC

**Comment by arnabghose997** [comment]
@PolkachuIntern 

The `final_genesis.json` and `final_peers.txt` has been corrected and updated. Please make sure to incorporate it. Follow the below link for next steps:

https://github.com/hypersign-protocol/networks/tree/master/testnet/jagrat#after-final-genesis-release

**Pull request merged**
