### PR TITLE
Brightlystake-gentx

### PR DESCRIPTION
**Pull request by Staking7pc**

### CODE REVIEW

**Review by arnabghose997 — CHANGES_REQUESTED** [review]
@Staking7pc The `minimum self delegation` should be `100000000000`, instead of `1`. Please make the necessary change.

**Comment by Staking7pc** [comment]
Changes done @arnabghose997

**Review by arnabghose997 — APPROVED** [review]
@Staking7pc 

Congratulations on being selected as a testnet validator! Keep an eye on this repo for `final_genesis.json` and `final_peers.json`.

We are expected to start our blockchain nodes on 28th September, 4:30 PM UTC

**Comment by Staking7pc** [comment]
@arnabghose997 Cheers bud! looking forward to it

**Pull request merged**
