### PR TITLE
Add StakeAngle gentx and peer

### PR DESCRIPTION
**Pull request by Cryptoperchik**

### CODE REVIEW

**Review by arnabghose997 — CHANGES_REQUESTED** [review]
@Cryptoperchik The `minimum self delegation` should be `100000000000`, instead of `1`. Please make the necessary change

**Review by arnabghose997 — CHANGES_REQUESTED** [review]
@Cryptoperchik 
It seems you have directly edited the gentx file. This would cause an error, since your earlier gentx has a signature.

So, basically you have to create a new gentx file (by following the pre genesis validator steps) and push it to this PR.

**Comment by Cryptoperchik** [comment]
> @Cryptoperchik It seems you have directly edited the gentx file. This would cause an error, since your earlier gentx has a signature.
> 
> So, basically you have to create a new gentx file (by following the pre genesis validator steps) and push it to this PR.

I generated a new gentx actually and then entered its content here. I think it should be fine since gentx now has a new signature

**Review by arnabghose997 — COMMENTED** [review]
My Apologies! I didn't notice the signature difference. Thanks for the update

**Review by arnabghose997 — APPROVED** [review]
@Cryptoperchik 

Congratulations on being selected as a testnet validator! Keep an eye on this repo for `final_genesis.json` and `final_peers.json`.

We are expected to start our blockchain nodes on 28th September, 4:30 PM UTC

**Comment by arnabghose997** [comment]
@Cryptoperchik 

The `final_genesis.json` and `final_peers.txt` has been corrected and updated. Please make sure to incorporate it. Follow the below link for next steps:

https://github.com/hypersign-protocol/networks/tree/master/testnet/jagrat#after-final-genesis-release

**Pull request merged**
