### PR TITLE
Add gentx-NodeStake.json

### PR DESCRIPTION
**Pull request by nodestake**

### CODE REVIEW

**Review by arnabghose997 — CHANGES_REQUESTED** [review]
@nodestake  The `minimum self delegation` should be `100000000000`, instead of `1`. Please make the necessary change.

**Comment by nodestake** [comment]
@arnabghose997 We fixed the minimum self delegation to be 100000000000 now

**Comment by arnabghose997** [comment]
@nodestake 

It seems you have directly edited the gentx file. This would cause an error, since your earlier gentx has a signature.

So, basically you have to create a new gentx file (by following the pre genesis validator steps) and push it to this PR.

**Review by arnabghose997 — COMMENTED** [review]
LGTM

**Comment by iwbinb** [comment]
Yes. It is OK.
We were experienced on gentx. ^-^

**Review by arnabghose997 — APPROVED** [review]
@nodestake 

Congratulations on being selected as a testnet validator! Keep an eye on this repo for `final_genesis.json` and `final_peers.json`.

We are expected to start our blockchain nodes on 28th September, 4:30 PM UTC

**Comment by arnabghose997** [comment]
@nodestake 

The `final_genesis.json` and `final_peers.txt` has been corrected and updated. Please make sure to incorporate it. Follow the below link for next steps:

https://github.com/hypersign-protocol/networks/tree/master/testnet/jagrat#after-final-genesis-release

**Comment by nodestake** [comment]
@arnabghose997 OK. No problem

**Pull request merged**
