### PR TITLE
Add TC Network gentx

### PR DESCRIPTION
**Pull request by trulacgc-tcnetwork**

### CODE REVIEW

**Comment by arnabghose997** [comment]
@trulacgc-tcnetwork  We found that you haven't provided the necessary documents in the KYC application. Please complete your KYC process in order to be considered for becoming a testnet validator.

**Comment by trulacgc-tcnetwork** [comment]
We have already done KYC process, please look at again, thanks.

**Comment by arnabghose997** [comment]
@trulacgc-tcnetwork Thanks

**Review by arnabghose997 — APPROVED** [review]
@trulacgc-tcnetwork 

Congratulations on being selected as a testnet validator! Keep an eye on this repo for `final_genesis.json` and `final_peers.json`.

We are expected to start our blockchain nodes on 28th September, 4:30 PM UTC

**Comment by arnabghose997** [comment]
@trulacgc-tcnetwork 

The `final_genesis.json` and `final_peers.txt` has been corrected and updated. Please make sure to incorporate it. Follow the below link for next steps:

https://github.com/hypersign-protocol/networks/tree/master/testnet/jagrat#after-final-genesis-release


If you haven't joined our Discord server, please join our server as discussions related to Hyperign Identity Network, such as governance proposals, node upgarades will happen over there. Below is the link to join:

https://discord.gg/ANpSb2dz

**Pull request merged**
